modules_dir = "artifacts/"

[[module]]
    name = "opensea_testnet_api"
    logger_enabled = true

    [module.mounted_binaries]
    curl = "/usr/bin/curl"

[[module]]
    name = "rarible_testnet_api"
    logger_enabled = true

    [module.mounted_binaries]
    curl = "/usr/bin/curl"